import { nanoid } from 'nanoid';
import { FaHtml5, FaJs, FaReact, FaNode } from 'react-icons/fa';
import { SiTypescript, SiCsharp } from "react-icons/si";

export const links = [
  // { id: nanoid(), href: '#home', text: 'home' },
  { id: nanoid(), href: '#skills', text: 'skills' },
  { id: nanoid(), href: '#projects', text: 'projects' },
];

export const skills = [
  {
    id: nanoid(),
    title: 'HTML&CSS',
    icon: <FaHtml5 className='h-16 w-16 text-blue-500' />,
    text: 'Highly skilled in HTML & CSS, adeptly crafting visually appealing and responsive websites for optimal user experiences.',
  },
  {
    id: nanoid(),
    title: 'Javascript',
    icon: <FaJs className='h-16 w-16 text-blue-500' />,
    text: 'Expertise in JavaScript, building interactive and dynamic web applications with a focus on seamless user interactions and functionality.',
  },
  {
    id: nanoid(),
    title: 'Typescript',
    icon: <SiTypescript className='h-16 w-16 text-blue-500' />,
    text: 'Middle proficiency in TypeScript, developing large-size full-stack applications with React.',
  },
  {
    id: nanoid(),
    title: 'React',
    icon: <FaReact className='h-16 w-16 text-blue-500' />,
    text: 'Advanced proficiency in React, developing efficient and interactive front-end applications with a strong emphasis on component-based architecture.',
  },
  {
    id: nanoid(),
    title: 'Node.js',
    icon: <FaNode className='h-16 w-16 text-blue-500' />,
    text: 'Middle skills in NodeJs, developing efficient and interactive full-stack applications with React.',
  },
  {
    id: nanoid(),
    title: 'ASP.NET Core',
    icon: <SiCsharp className='h-16 w-16 text-blue-500' />,
    text: 'Good proficiency in C#, developing efficient and interactive full-stack applications with React and .NET Core.',
  },
  // add typescript
];

export const projects = [
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://joyful-smakager-949ff9.netlify.app/',
    github: 'https://github.com/Fjdsilv/user-search',
    title: 'github search',
    text: 'github search is a dummy project build with React(useState, useEffect, ContextAPI and useReducer), React-Router-Dom, github-API, Tailwindcss and DaisyUI Responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://glowing-axolotl-89543f.netlify.app/',
    github: 'https://github.com/Fjdsilv/BAV-mini-bank/',
    title: 'BAV Mini Bank',
    text: 'BAV Mini Bank Is A Dummy Project Build With React(UseState), Redux(Toolkit and Thunk), React-Router-Dom, Frankfurter-API, Tailwindcss and DaisyUI Responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://neon-cajeta-4e64ef.netlify.app/',
    github: 'https://github.com/Fjdsilv/BuddyBear-Brewery/',
    title: 'BuddyBear Brewery',
    text: 'BuddyBear Brewery is a dummy project build with React(useState, useEffect, ContextAPI and useReducer), React-Router-Dom, Axios, Open Brewery DB-API, Tailwindcss and DaisyUI Responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://buddy-drinks.vercel.app/',
    github: 'https://github.com/Fjdsilv/buddy-drinks',
    title: 'buddy drinks',
    text: 'buddy drinks is a dummy project build with React, React-Router-Dom, Axios, React-Query(client), Cocktails DB-API and Styled-components Responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://polite-sable-7e312e.netlify.app/',
    github: 'https://github.com/Fjdsilv/pizza-recipe-directory/',
    title: 'Pizza Recipe Directory',
    text: 'Pizza Recipe Directory is a dummy project build with React(useState and ContextAPI), React-Router-Dom, HTML and CSS Responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://deluxe-dodol-cf1cf0.netlify.app/',
    github: 'https://github.com/Fjdsilv/unsplash-like-images',
    title: 'unsplash like images',
    text: 'unsplash like images Is A Dummy Project Build With React(UseState, UseEffect and ContextAPI), React-Query(Client), axios, unsplash-API, HTML and CSS(Flexbox and Grid) Responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://chic-praline-de47aa.netlify.app/',
    github: 'https://github.com/Fjdsilv/Buddy-shop-cart/',
    title: 'Buddy Shop Cart',
    text: 'Buddy Shop Cart Is A Dummy Project Build With React(UseState), Redux(Toolkit and Thunk),  Dummy-API, HTML and CSS(Grid) Responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://legendary-manatee-d0a784.netlify.app/',
    github: 'https://github.com/Fjdsilv/Buddy-Movie-Search/',
    title: 'Buddy Movie Search',
    text: 'Buddy Movie Search is a dummy project build with React(useState and useEffect), OMDb-API, localStorage and React Boostrap Responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://buddy-mini-blog.vercel.app/',
    github: 'https://github.com/Fjdsilv/buddy-mini-blog/',
    title: 'Buddy Mini Blog',
    text: 'Buddy Mini Blog Is A Project Build With React(UseState And UseEffect), Redux(Toolkit), Axios, GNews-API, React-Oauth/Google And Material-UI Responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://stirring-stardust-b3cf55.netlify.app/',
    github: 'https://github.com/Fjdsilv/social-media-invite/',
    title: 'Social Media Invite',
    text: 'Social Media Invite Is A Dummy Project Build With React(UseState), Redux(Toolkit),  HTML And CSS(Flexbox) Responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://weather-buddy-jet.vercel.app/',
    github: 'https://github.com/Fjdsilv/weather-buddy',
    title: 'weather buddy',
    text: 'weather buddy is a project build with React(useState and useEffect), axios, OpenWeatherMap-API, HTML and CSS(Flexbox) responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/326503/pexels-photo-326503.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://famous-cassata-89f522.netlify.app/',
    github: 'https://github.com/Fjdsilv/buddy-shop/',
    title: 'Buddy Shop',
    text: 'Buddy Shop is a project build with React(useState, ContextAPI and useReducer), React-Router-Dom, HTML and CSS responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/326503/pexels-photo-326503.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://shop-cart-pi-three.vercel.app/',
    github: 'https://github.com/Fjdsilv/shop-cart/',
    title: 'Shop Cart',
    text: 'Shop Cart is a project build with React(useState, ContextAPI and useReducer), Dummy-API, HTML and CSS(Flexbox and Grid) responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/12883026/pexels-photo-12883026.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://feedback-rate-dummy.vercel.app/',
    github: 'https://github.com/Fjdsilv/feedback-rate-dummy',
    title: 'feedback rate Dummy',
    text: 'feedback rate Dummy is a project build with React(useState, useEffect, useReducer and ContextAPI), HTML and CSS(Flexbox) responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://friends-split-bill.vercel.app/',
    github: 'https://github.com/Fjdsilv/friends-split-bill',
    title: 'friends split bill',
    text: 'friends split bill is a project build with React(useState), HTML and CSS(Flexbox) responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://to-do-list-lime-gamma.vercel.app/',
    github: 'https://github.com/Fjdsilv/to-do-list',
    title: 'To-Do List',
    text: 'To-Do List is a project build with React(useState), LocalStorage, HTML and CSS(Grid) responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://buddy-sticky-notes.vercel.app/',
    github: 'https://github.com/Fjdsilv/buddy-sticky-notes',
    title: 'buddy sticky notes',
    text: 'buddy sticky notes is a project build with React(useState and useEffect), LocalStorage and Tailwindcss responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/12883026/pexels-photo-12883026.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://tubular-belekoy-351d9c.netlify.app/',
    github: 'https://github.com/Fjdsilv/Blog-Post-Dummy',
    title: 'Blog Post Dummy',
    text: 'Blog Post Dummy is a project build with React(useState), LocalStorage, HTML and CSS responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/12883026/pexels-photo-12883026.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://supermarket-list-roan.vercel.app/',
    github: 'https://github.com/Fjdsilv/supermarket-list',
    title: 'supermarket list',
    text: 'supermarket list is a project build with React(useState), HTML and CSS(Flexbox) responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/12883026/pexels-photo-12883026.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://stalwart-bienenstitch-42114e.netlify.app/',
    github: 'https://github.com/Fjdsilv/lorem-ipsum-dummy',
    title: 'Lorem Ipsum Dummy',
    text: 'Lorem Ipsum Dummy is a project build with React(useState), HTML and CSS responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/12883026/pexels-photo-12883026.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://rock-paper-scissors-theta-eight.vercel.app/',
    github: 'https://github.com/Fjdsilv/rock-paper-scissors/',
    title: 'rock paper scissors',
    text: 'rock paper scissors is a project build with React(useState and useEffect), HTML and CSS(Grid) responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/12883026/pexels-photo-12883026.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://saints-memory-game.vercel.app/',
    github: 'https://github.com/Fjdsilv/saints-memory-game/',
    title: 'saints memory game',
    text: 'saints memory game is a project build with React(useState and useEffect), HTML and CSS(Grid) responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://dashing-elf-9dec2a.netlify.app/',
    github: 'https://github.com/Fjdsilv/Metalurgica-Veneza-landpage',
    title: 'Metalúrgica Veneza',
    text: 'Metalúrgica Veneza is a landPage build with HTML, CSS, Bootstrap, VanillaJS, JQuery, ScrollReveal.js and baguetteBox.js Responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://eloquent-genie-33d6b3.netlify.app/',
    github: 'https://github.com/Fjdsilv/portfolio-1.0',
    title: 'Felipe Silva Portfolio 1.0',
    text: 'Felipe Silva Portfolio 1.0 is landPage build with HTML, CSS(Flexbox), Normalizecss and VanillaJS  Responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://brilliant-daffodil-e66f19.netlify.app/',
    github: 'https://github.com/Fjdsilv/Fast-Pizza-Delivery-landpage',
    title: 'Fast Pizza Delivery',
    text: 'Fast Pizza Delivery is a dummy landPage build with HTML, CSS, Normalizecss, VanillaJS, JQuery, and ScrollReveal.js Responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://luminous-paprenjak-c23822.netlify.app/',
    github: 'https://github.com/Fjdsilv/IPromise-Co-landpage/',
    title: 'IPromise Co.',
    text: 'IPromise Co. is a dummy landPage build with HTML, CSS, Normalizecss, VanillaJS, JQuery, and ScrollReveal.js Responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://dainty-sorbet-47aecb.netlify.app/',
    github: 'https://github.com/Fjdsilv/Classic-Barbershop-landpage',
    title: 'Classic Barbershop',
    text: 'Classic Barbershop is a dummy landPage build with HTML, CSS(Flexbox), Normalizecss, VanillaJS, JQuery, ScrollReveal.js and Owl Carousel Library Responsive.',
  },
  {
    id: nanoid(),
    // img: 'https://images.pexels.com/photos/2148222/pexels-photo-2148222.jpeg?auto=compress&cs=tinysrgb&w=800',
    url: 'https://steady-baklava-bb68df.netlify.app/',
    github: 'https://github.com/Fjdsilv/Ferrari-F40-Tribute-landpage',
    title: 'Ferrari F40 Tribute',
    text: 'Ferrari F40 Tribute is a Dummmy LandPage build with HTML, CSS and Tailwindcss Responsive.',
  },
];
